# Generated by Django 5.0.2 on 2024-02-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_alter_customuser_options_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='sm_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='st_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
