# Generated by Django 5.0.2 on 2024-02-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_alter_ordertable_teacher_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='teachers_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
