# Generated by Django 5.0.2 on 2024-02-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0007_alter_ordertable_delivered_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
