# Generated by Django 5.0.2 on 2024-03-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0009_alter_ordertable_teacher_recieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertable',
            old_name='customer',
            new_name='user',
        ),
    ]
