# Generated by Django 5.0.2 on 2024-03-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0012_rename_is_staff_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
