# Generated by Django 5.0.2 on 2024-03-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0013_rename_is_admin_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='in_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending order'), ('Partially In Stock', 'Order is partially in Stock'), ('Fully In Stock', 'Order is fully in Stock'), ('Fully recieved', 'Order is fully recieved to teacher')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='teacher_recieved',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
