# Generated by Django 5.0.2 on 2024-03-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0015_alter_ordertable_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertable',
            options={'ordering': ['-order_date']},
        ),
        migrations.AddField(
            model_name='ordertable',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
