# Generated by Django 5.0.2 on 2024-03-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0016_alter_ordertable_options_ordertable_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='editable_dates',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
