# Generated by Django 5.0.2 on 2024-03-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0017_ordertable_editable_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='editable_dates',
        ),
        migrations.AddField(
            model_name='customuser',
            name='editable_dates',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
