# Generated by Django 5.0.2 on 2024-03-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0018_remove_ordertable_editable_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='editable_dates',
        ),
    ]
